{
 "title": "Proxmox",
 "description": "Proxmox",
 "tags": [ "Proxmox" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Cluster info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node status",
     "type": "stat",
     "gridPos": { "h": 11, "w": 4, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "pve_node_info", "legendFormat": "{{name}}" }
     ]
    },
    {
     "title": "Version",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "pve_version_info", "legendFormat": "{{version}}" }
     ]
    },
    {
     "title": "Storage status",
     "type": "stat",
     "gridPos": { "h": 11, "w": 16, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "pve_storage_info", "legendFormat": "{{node}} : {{storage}}" }
     ]
    },
    {
     "title": "Running VMs",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum by (job) (pve_guest_info) and on (job) pve_up==1",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "VMs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "VMs",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "sum by(id, name, node) (pve_guest_info) "
    },
    {
     "expr": "sum by(id) (pve_up{id!~\"$node\"} and on (id) pve_guest_info)"
    },
    {
     "expr": "sum by (id) (pve_cpu_usage_limit and on (id) pve_guest_info)"
    },
    {
     "expr": "sum by (id) (pve_disk_size_bytes and on (id) pve_guest_info)"
    },
    {
     "expr": "sum by (id) (pve_memory_size_bytes and on (id) pve_guest_info)"
    },
    {
     "expr": "sum by (id) (pve_memory_usage_bytes{template!=\"1\"} / pve_memory_size_bytes and on (id) pve_guest_info and on (id) pve_up==1)"
    }
   ]
  },
  {
   "title": "VM CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(pve_cpu_usage_ratio{id!~\"$node\"} / pve_cpu_usage_limit) * on (id) group_left(name) pve_guest_info",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "VM memory usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(pve_memory_usage_bytes{id!~\"$node\"}) * on (id) group_left(name) pve_guest_info",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Disk IO/s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "((irate(pve_disk_write_bytes[$__rate_interval]) + irate(pve_disk_read_bytes[$__rate_interval])) * on(id) group_left(name, type) pve_guest_info) and on(id) pve_up == 1",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network IO/s",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(irate(pve_network_receive_bytes[$__rate_interval]) * on(id) group_left(name) pve_guest_info) and on(id) pve_up == 1",
     "legendFormat": "recv {{name}}"
    },
    {
     "expr": "(irate(pve_network_transmit_bytes[$__rate_interval])* on(id) group_left(name) pve_guest_info) and on(id) pve_up == 1",
     "legendFormat": "trans {{name}}"
    }
   ]
  }
 ]
}